"""empty message

Revision ID: 319e666e4406
Revises: a1d0e5dad21f
Create Date: 2019-05-26 14:21:03.521501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '319e666e4406'
down_revision = 'a1d0e5dad21f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='companies'
    )
    op.add_column('companies', sa.Column('plan_id', sa.Integer(), nullable=True), schema='companies')
    op.create_foreign_key(None, 'companies', 'plans', ['plan_id'], ['id'], source_schema='companies', referent_schema='companies')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', schema='companies', type_='foreignkey')
    op.drop_column('companies', 'plan_id', schema='companies')
    op.drop_table('plans', schema='companies')
    # ### end Alembic commands ###
