"""empty message

Revision ID: ba1603d14816
Revises: f4483ddb8b01
Create Date: 2018-11-28 18:13:34.601381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba1603d14816'
down_revision = 'f4483ddb8b01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('identifier', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='companies'
    )
    op.create_table('user_companies',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.companies.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'company_id'),
    schema='companies'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_companies', schema='companies')
    op.drop_table('companies', schema='companies')
    # ### end Alembic commands ###
