openapi: "3.0.0"
info:
  title: Users Service
  version: 1.0.0
  description: Users Service API documentation
servers:
  - url: http://localhost:5002
  - url: http://stage.onelike.gusisoft.cl
tags:
  - name: Companies
    description: Companies Operations
  - name: Service Health
    description: Service Health Status
paths:
  /companies:
    get:
      tags:
        - Companies
      summary: List Companies
      description: List Companies by user Token
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Companies List
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/Company"
        '403':
          description: Forbidden.
          content:
            application/json:
              schema:
                $ref: "#components/responses/Forbidden"
    post:
      tags:
        - Companies
      summary: Create a Company
      description: Create a Company
      security:
        - bearerAuth: []
      requestBody:
        description: Company data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/CompanyCreate'
      responses:
        '201':
          description: Company created
          content:
            application/json:
              schema:
                $ref: "#components/schemas/Company"
        '400':
          description: Invalid request.
          content:
            application/json:
              schema:
                $ref: "#components/responses/BadRequest"
        '403':
          description: Forbidden.
          content:
            application/json:
              schema:
                $ref: "#components/responses/Forbidden"
  /companies/{id}:
    get:
      tags:
        - Companies
      summary: Get Company
      description: Get Company by user Token
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: Company id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Company Get
          content:
            application/json:
              schema:
                $ref: "#components/schemas/Company"
        '403':
          description: Forbidden.
          content:
            application/json:
              schema:
                $ref: "#components/responses/Forbidden"
        '404':
          description: Company not found.
          content:
            application/json:
              schema:
                $ref: "#components/responses/NotFound"
  /companies/{id}/users:
    get:
      tags:
        - Companies
      summary: Get Company users
      description: Get Company users
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: Company id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Company Users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/User"
        '403':
          description: Forbidden.
          content:
            application/json:
              schema:
                $ref: "#components/responses/Forbidden"
        '404':
          description: Company not found.
          content:
            application/json:
              schema:
                $ref: "#components/responses/NotFound"
  /companies/users:
    get:
      tags:
        - Companies
      summary: Get Company users
      description: Get Company users
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: Company id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Company Users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/User"
        '403':
          description: Forbidden.
          content:
            application/json:
              schema:
                $ref: "#components/responses/Forbidden"
        '404':
          description: Company not found.
          content:
            application/json:
              schema:
                $ref: "#components/responses/NotFound"
  /companies-service/health:
    get:
      tags:
        - Service Health
      summary: Service health
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Health"
components:
  schemas:
    Company:
      properties:
        id:
          type: integer
          format: int64
          description: Company id
        identifier:
          type: string
          description: Company national identifier
        name:
          type: string
          description: Company name
    Health:
      properties:
        message:
          type: string
          description: Health status
  requestBodies:
    CompanyCreate:
      properties:
        identifier:
          type: string
          description: Company TAX identifier
        name:
          type: string
          description: Company name
  responses:
    BadRequest:
      properties:
        message:
          type: string
          description: Error cause
    NotFound:
      properties:
        message:
          type: string
          description: Error cause
    Forbidden:
      properties:
        message:
          type: string
          description: Error cause

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
